openapi: '3.0.2'
info:
  title: Node Store API
  version: '1.0'
components:
  securitySchemes:
    JWT:
      type: apiKey
      in: header
      name: Authorization
paths:
  /:
    get:
      responses:
        '200':
          description: OK
  /product/:
    get:
      security:
        - JWT: []
      tags:
        - Product
      description: 'Get all products:'
      parameters: []
      responses:
        '200':
          description: OK
        '401':
          description: RESTRICTED ACCESS ERROR
    post:
      security:
        - JWT: []
      tags:
        - Product
      description: 'Create a product:'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                price:
                  type: number
                  minimum: 0
                description:
                  type: string
                active:
                  type: boolean
                slug:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
        '401':
          description: RESTRICTED ACCESS ERROR
  /product/id/{id}:
    delete:
      security:
        - JWT: []
      tags:
        - Product
      description: 'Delete one product with ID:'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: THe product ID 
      responses:
        '200':
          description: OK
        '401':
          description: RESTRICTED ACCESS ERROR
    put:
      security:
        - JWT: []
      tags:
        - Product
      description: 'Update one product with ID:'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: THe product ID 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                price:
                  type: number
                  minimum: 0
                description:
                  type: string
                slug:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: RESTRICTED ACCESS ERROR
  /customer/:
    get:
      security:
        - JWT: []
      tags:
        - Customer
      description: Get infos Customers
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    post:
      tags:
        - Customer
      description: Create new Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
  /customer/login:
    post:
        tags:
          - Customer
        description: Login Customer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: OK
          '404':
            description: CUSTOMER NOT FOUND
          '400':
            description: ERROR
  /customer/refresh:
    post:
      security:
        - JWT: []
      tags:
        - Customer
      description: Login Customer
      responses:
        '200':
          description: OK
        '404':
          description: CUSTOMER NOT FOUND
        '400':
          description: ERROR
  /order/:
    get:
      security:
        - JWT: []
      tags:
        - Order
      description: Get all orders
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
    post:
      security:
        - JWT: []
      tags:
        - Order
      description: Create new Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      quantity:
                        type: integer
                        minimum: 1
                      price:
                        type: number
                        minimum: 0
                      product:
                        type: string
      responses:
        '200':
          description: OK
        '400':
          description: ERROR
